### ISSUE TITLE
PayPal Here crashes on return to calling app after credit card payment

### ISSUE THREAD

**Issue by cdewberry** [paypal/here-sideloader-api-samples#53]
I'm building the v2 here-sideloader-api-sample Android app with Android Studio - unfortunately PPHere is crashing on return to the sample app IF I HAVE SWIPED a credit card (or entered in a card number). Accepting cash or canceling payment returns me to the sample app. The invoice amount is deducted from the payee and added to the merchant, but when I tap 'New Sale', PayPal Here crashes. I tried to minimize the ReturnURL to simply pass back Type=UNKNOWN, but it still crashes.

Is there something I need to setup on the PayPal account that I am using?

This seems to be similar to #39 but that issue was solved by removing &as=b64. I do not have this in my URL.
Also similar to #42 but I have URL encoded everything.
I'm using PayPal here 2.9.0, Android version 7.0 on a Galaxy Tab S3. I have used a live PayPal account and a sandbox account.

Here is my URL:
paypalhere://takePayment/v2?accepted=card&returnUrl=pphsample%3A%2F%2FhandleResponse%3FType%3DUNKNOWN&invoice=%7B%22currencyCode%22%3A%22USD%22%2C%22discountPercent%22%3A%220%22%2C%22itemList%22%3A%7B%22item%22%3A%5B%7B%22description%22%3A%22I%20Love%20APIs%20shirt%22%2C%22name%22%3A%22T-Shirt%22%2C%22quantity%22%3A1.0%2C%22taxName%22%3A%22Sales%20Tax%22%2C%22taxRate%22%3A%220.00%22%2C%22unitPrice%22%3A1.0%7D%5D%7D%2C%22merchantEmail%22%3A%22merchant%40test.com%22%2C%22number%22%3A%2270%22%2C%22payerEmail%22%3A%22customer%40test.com%22%2C%22paymentTerms%22%3A%22DueOnReceipt%22%7D&step=choosePayment

Here is the call stack where PPHere crashes:
                                               --------- beginning of crash
11-14 10:31:54.574 28770-28770/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.paypal.here, PID: 28770
                                                   java.lang.RuntimeException: Unable to resume activity {com.paypal.here/com.paypal.here.activities.charge.ChargeActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'com.paypal.merchant.sdk.domain.SecureCreditCard com.paypal.merchant.sdk.domain.TransactionRecord.getSecureCreditCard()' on a null object reference
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3841)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3882)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1689)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6780)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.paypal.merchant.sdk.domain.SecureCreditCard com.paypal.merchant.sdk.domain.TransactionRecord.getSecureCreditCard()' on a null object reference
                                                       at com.paypal.here.services.thirdpartyintegration.ThirdPartyInvoice.convertPaymentType(SourceFile:313)
                                                       at com.paypal.here.services.thirdpartyintegration.ThirdPartyInvoice.createThirdPartyReturnUrl(SourceFile:276)
                                                       at com.paypal.here.activities.charge.BaseChargePresenter.handleThirdPartyCallback(SourceFile:832)
                                                       at com.paypal.here.activities.charge.BaseChargePresenter.onPreviousTransactionCompleted(SourceFile:480)
                                                       at com.paypal.here.activities.charge.BaseChargePresenter.initOrder(SourceFile:454)
                                                       at com.paypal.here.activities.charge.BaseChargePresenter.onResume(SourceFile:434)
                                                       at com.paypal.here.activities.charge.AudioChargePresenter.onResume(SourceFile:81)
                                                       at com.paypal.here.activities.charge.orderentry.ChargePresenterDelegate.onResume(SourceFile:402)
                                                       at com.paypal.here.activities.charge.ChargeActivity.onResume(SourceFile:620)
                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
                                                       at android.app.Activity.performResume(Activity.java:7094)
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3818)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3882) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1689) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6780) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386) 

Any help very much appreciated!

**Comment by paypalsathya** [comment]
We are looking into this issue and will get back to you.
Chances are, sideloader might be broken in the latest release of the app.
We are working on a fix and should be made available next week.

Apologies for the delayed response 😞

**Comment by cdewberry** [comment]
That would be great! I'll be looking forward to it.

Caroline Dewberry
Software Engineer
Book Systems, Inc.
(256)533-9746

**Comment by DJ92** [comment]
Hey @cdewberry , this has been fixed in the latest release v3.2.3. Let us know if you have any questions/concerns.
